# 27 May 2018
# A. Vershinina
# Goal: parse genome coverage file from bedtools
# In: genome coverage table generated by bedtools. 
# Bedtools command should be something like:
# bedtools genomecov -ibam genome.bam -g genome.info > genome.cov.tab
# out: coverage graph, mean and SD coverage

args = commandArgs(trailingOnly=TRUE)
if (length(args) == 0){
  cat("Syntax: Rscript coverage_stats.R [ genome.cov.tab]\n")
  cat("Example: Rscript coverage_stats.R  horse.cov.tab\n")
  quit()
}

df <- read.csv(args[1], sep = "\t", header=F)
n <- basename(args[1]) 
n <- substr(n, 1, nchar(n)-4)
df_genome <- df[df$V1=="genome",]
cov <- as.numeric(df_genome$V2)
frequency <- as.numeric(df_genome$V3)
dta <- data.frame(cov, frequency)
barplot(dta$frequency, names.arg = dta$cov, xlim = c(0,100), main=paste("Coverage plot for", n), xlab = "cov", ylab="freq")
png(paste(n, "png", sep="."))
# make plot
dev.off()


m = sum(dta$cov * dta$frequency) / sum(dta$frequency)
sigma = sqrt(sum((dta$cov - m)**2 * dta$frequency) / (sum(dta$frequency)-1))
stat$sample = n
stat$sigma = sigma
stat$m = m
cat(stat, file=paste(n, "stat.txt", sep="."), sep="")
