#!/usr/local/bin/bash
# 11 Apr 2018
# A. Vershinina
# Goal: Run vcf filtering on few files generated by different genotype callers. This code also removes indels.


ANT=*.h.vcf.bgz
MPILE=*.mpile.vcf.gz

MIN_DP=5
MAX_DP=60
MIN_Q=25
MIN_GQ=20

for f in $ANT; do
	NAME=$(echo ${f} | sed 's/[.].*//')
	vcftools --gzvcf $f --remove-indels --recode --recode-INFO-all --minDP $MIN_DP --maxDP $MAX_DP --minQ $MIN_Q --minGQ $MIN_GQ --max-missing 1 --stdout |  bgzip > ${NAME}.ant.mindp${MIN_DP}.maxdp${MAX_DP}.vcf.gz
	wait 
	echo "File $f filtered"
	tabix -p vcf ${NAME}.ant.mindp${MIN_DP}.maxdp${MAX_DP}.vcf.gz
	wait
done

for f in $MPILE; do
	NAME=$(echo ${f} | sed 's/[.].*//')
	vcftools --gzvcf $f --remove-indels --recode --recode-INFO-all --minDP $MIN_DP --maxDP $MAX_DP --minQ $MIN_Q --minGQ $MIN_GQ --max-missing 1 --stdout |  bgzip > ${NAME}.mpile.mindp${MIN_DP}.maxdp${MAX_DP}.vcf.gz
	wait 
	echo "File $f filtered"
	tabix -p vcf ${NAME}.mpile.mindp${MIN_DP}.maxdp${MAX_DP}.vcf.gz
	wait
done

echo "All done"
